# Generated by Django 3.1.4 on 2021-01-26 01:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dm', models.UUIDField()),
                ('campaign_name', models.CharField(max_length=64)),
                ('campaign_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.UUIDField()),
                ('player_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.UUIDField()),
                ('scene_id', models.UUIDField(default=uuid.uuid4)),
                ('character_id', models.UUIDField(null=True)),
                ('character_x_pos', models.FloatField(null=True)),
                ('character_y_pos', models.FloatField(null=True)),
                ('character_z_pos', models.FloatField(null=True)),
                ('character_x_rot', models.FloatField(null=True)),
                ('character_y_rot', models.FloatField(null=True)),
                ('character_z_rot', models.FloatField(null=True)),
                ('character_x_scale', models.FloatField(null=True)),
                ('character_y_scale', models.FloatField(null=True)),
                ('character_z_scale', models.FloatField(null=True)),
                ('asset_id', models.UUIDField(null=True)),
                ('asset_x_pos', models.FloatField(null=True)),
                ('asset_y_pos', models.FloatField(null=True)),
                ('asset_z_pos', models.FloatField(null=True)),
                ('asset_x_rot', models.FloatField(null=True)),
                ('asset_y_rot', models.FloatField(null=True)),
                ('asset_z_rot', models.FloatField(null=True)),
                ('asset_x_scale', models.FloatField(null=True)),
                ('asset_y_scale', models.FloatField(null=True)),
                ('asset_z_scale', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('klass', models.CharField(max_length=32)),
                ('level', models.IntegerField(default=1)),
                ('background', models.CharField(max_length=64)),
                ('playerName', models.CharField(max_length=64)),
                ('race', models.CharField(max_length=32)),
                ('alignment', models.CharField(default='Neutral', max_length=64)),
                ('XP', models.IntegerField(default=0)),
                ('armorClass', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField(default=30)),
                ('inspiration', models.BooleanField(default=False)),
                ('proficiencyBonus', models.IntegerField()),
                ('strengthMod', models.IntegerField()),
                ('dexMod', models.IntegerField()),
                ('conMod', models.IntegerField()),
                ('intelligenceMod', models.IntegerField()),
                ('wisdomMod', models.IntegerField()),
                ('charismaMod', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('con', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('strengthSave', models.IntegerField()),
                ('dexSave', models.IntegerField()),
                ('conSave', models.IntegerField()),
                ('intelligenceSave', models.IntegerField()),
                ('wisdomSave', models.IntegerField()),
                ('charismaSave', models.IntegerField()),
                ('acrobatics', models.IntegerField()),
                ('animalHandling', models.IntegerField()),
                ('arcana', models.IntegerField()),
                ('athletics', models.IntegerField()),
                ('deception', models.IntegerField()),
                ('history', models.IntegerField()),
                ('insight', models.IntegerField()),
                ('intimidation', models.IntegerField()),
                ('investigation', models.IntegerField()),
                ('medicine', models.IntegerField()),
                ('nature', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('persuasion', models.IntegerField()),
                ('religion', models.IntegerField()),
                ('sleightOfHand', models.IntegerField()),
                ('stealth', models.IntegerField()),
                ('survival', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('currentHP', models.IntegerField()),
                ('totalHitDice', models.IntegerField()),
                ('currentHitDice', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_management.campaign')),
            ],
        ),
    ]
