# Generated by Django 3.1.4 on 2021-01-29 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneAssetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.UUIDField()),
                ('scene_id', models.UUIDField(default=uuid.uuid4)),
                ('asset_id', models.CharField(max_length=256)),
                ('asset_x_pos', models.FloatField(null=True)),
                ('asset_y_pos', models.FloatField(null=True)),
                ('asset_z_pos', models.FloatField(null=True)),
                ('asset_x_rot', models.FloatField(null=True)),
                ('asset_y_rot', models.FloatField(null=True)),
                ('asset_z_rot', models.FloatField(null=True)),
                ('asset_x_scale', models.FloatField(null=True)),
                ('asset_y_scale', models.FloatField(null=True)),
                ('asset_z_scale', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneCharacterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.UUIDField()),
                ('scene_id', models.UUIDField()),
                ('character_id', models.UUIDField(null=True)),
                ('character_x_pos', models.FloatField(null=True)),
                ('character_y_pos', models.FloatField(null=True)),
                ('character_z_pos', models.FloatField(null=True)),
                ('character_x_rot', models.FloatField(null=True)),
                ('character_y_rot', models.FloatField(null=True)),
                ('character_z_rot', models.FloatField(null=True)),
                ('character_x_scale', models.FloatField(null=True)),
                ('character_y_scale', models.FloatField(null=True)),
                ('character_z_scale', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_x_pos',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_x_rot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_x_scale',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_y_pos',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_y_rot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_y_scale',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_z_pos',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_z_rot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='asset_z_scale',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_x_pos',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_x_rot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_x_scale',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_y_pos',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_y_rot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_y_scale',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_z_pos',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_z_rot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='character_z_scale',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_scene_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_name',
            field=models.CharField(default='Default', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
