# Generated by Django 3.0.6 on 2021-02-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0002_auto_20210129_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sceneassetdata',
            name='campaign_id',
        ),
    ]
